<?php

$version = 0.1;

//***** GET DATA FROM USER ***************************

$ac_enginepower     = $_POST['ac_enginepower'];
$ac_engineunits     = $_POST['ac_engineunits'];

//***** CONVERT TO ENGLISH UNITS *********************

if($ac_engineunits == 1) {
  $ac_enginepower *= 1.341;
  }



//************************************************
//*                                              *
//*  Print out xml document                      *
//*                                              *
//************************************************

// estimate total linear-blade-inches from horsepower

$LBI = 5.3 * pow($ac_enginepower, 0.5);

// estimate number of blades and diameter from horsepower

if($ac_enginepower < 400) {
  $blades = 2;
  $dia = $LBI;
  }
elseif($ac_enginepower < 1400) {
  $blades = 3;
  $dia = $LBI * 0.666667; 
  }
else {
  $blades = 4;
  $dia = $LBI * 0.5;
  }

// estimate moment of inertia

$L = $LBI / $blades /12; // length each blade (feet)
$M = $L * 0.09317;       // mass each blade (slugs)
$ixx = $blades * (0.33333 * $M * $L * $L);

//*****************************************************
//                                                    *
//  Print XML file                                    *
//                                                    *
//*****************************************************

print("<xml version=\"1.0\"?>\n");
print("<!-- Generated by Aero-Matic to fit a $ac_enginepower ");
print("horsepower engine -->\n\n");
print("<FG_PROPELLER NAME=\"prop\">\n");
print("  IXX        $ixx\n");
print("  DIAMETER   $dia\n");
print("  NUMBLADES  $blades\n");
print("  MINPITCH   23\n");
print("  MAXPITCH   23\n");
print("  MINRPM    700\n");
print("  MAXRPM   2700\n");
print("  C_THRUST   11 1\n");
print("  0.0  0.936\n");
print("  0.1  0.927\n");
print("  0.2  0.918\n");
print("  0.3  0.909\n");
print("  0.4  0.828\n");
print("  0.5  0.738\n");
print("  0.6  0.063\n");
print("  0.7  0.049\n");
print("  0.8  0.036\n");
print("  0.9  0.020\n");
print("  1.0  0.004\n");
print("  C_POWER   11 1\n");
print("  0.0  0.0594\n");
print("  0.1  0.0585\n");
print("  0.2  0.0576\n");
print("  0.3  0.0558\n");
print("  0.4  0.0540\n");
print("  0.5  0.0522\n");
print("  0.6  0.0495\n");
print("  0.7  0.0432\n");
print("  0.8  0.0342\n");
print("  0.9  0.0225\n");
print("  1.0  0.0090\n");
print("</FG_PROPELLER>\n");

?>